[project]
name = "manuals-to-kg"
version = "0.1.0"
description = "Simple example for cocoindex: extract triples from files and build knowledge graph."
requires-python = ">=3.11"
dependencies = ["cocoindex>=0.2.8"]

[tool.setuptools]
packages = []
