services:
  coco_db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: cocoindex
      POSTGRES_PASSWORD: cocoindex
      POSTGRES_DB: cocoindex
      POSTGRES_PORT: 5436
    ports:
      - "5436:5436"
    command: postgres -p 5436

  coco_api:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - coco_db
